## Admixture

#
# This script converts the vcf file from the original publication to a plink .bed file for
# analyis in Admixture, checking for the optimal number of populations (K = 1-9)
# using the cross-validation errors. In addition, this script calls an R-script (admixture_panel_plot.R)
# that plots the 9 Admixture plots for visualization.
#

# set working directory to Admixture folder, which should contain three sub-folders (DATA, FIGURES, SCRIPTS)

#
# set up vcf tools in docker biocontainers in order to convert vcf to plink
# need to have docker installed
#
docker pull biocontainers/vcftools:0.1.15

#
# make shortcut for vcftools, linking it to data
# USE YOUR INDIVIDUAL PATH TO ADMIXTURE FOLDER 
#
vcftools="docker run --rm -v /YOUR/ABSOLUTE/ROUTE/HERE/Admixture:/data biocontainers/vcftools:0.1.15 vcftools"

#
# convert from vcf to plink
#
$vcftools --vcf data/80missingdata.singleSNP.vcf --plink --out data/80missingdata.singleSNP

#
# convert ped to bed
# must have plink executable in DATA folder
#
DATA/plink --file DATA/80missingdata.singleSNP --make-bed --out DATA/80missingdata.singleSNP

#
# Run Admixture with cross-validation errors in loop
# make sure .fam and .bim files are in DATA folder, with .bed and admixture executable
#
cd DATA
for K in 1 2 3 4 5 6 7 8 9;
do ./admixture --cv 80missingdata.singleSNP.bed $K | tee log${K}.out; done

#
# write CV errors to text file, lowest CV error is most likely K value
#
grep -h CV log*.out | grep -oE '0.[0-9]*' >> Admixture.CVerrors.txt

#
# graph CV Errors using R script CVErrors_graph.R, lowest CV error is most likely K value
#
Rscript ../SCRIPTS/CVErrors_graph.R
mv CVerrors.pdf ../FIGURES

#
# graph admixture barplots in panel form using R script (admixture_panel_plot.R):
#
cd ..
Rscript SCRIPTS/admixture_panel_plot.R
